dirs:
  - .
useGitIgnore: true
aliveStatusCodes:
  - 200
  - 201
  - 204
  - 302
  - 304
ignorePatterns:
  - pattern: "^http://localhost.*$"
  - pattern: "^http://HOSTNAME:PORT.*$"
replacementPatterns:
  - pattern: ".md#.*$"
    replacement: ".md"
