dirs:
  - .
useGitIgnore: true
aliveStatusCodes:
  - 200
  - 201
  - 204
  - 302
  - 304
ignorePatterns:
  - pattern: "^http://localhost.*$"
  - pattern: "^http://HOSTNAME:PORT.*$"
  - pattern: "172\\.18\\.255\\.200"
  - pattern: "https://\\*kpt\\*\\.dev/"
  - pattern: "https://my-gitlab\\.com/joe\\.bloggs/blueprints\\.git"
  - pattern: "http://172\\.18\\.0\\.200:3000/nephio/"
replacementPatterns:
  - pattern: ".md#.*$"
    replacement: ".md"
