#---------------------------------------------------------------------
# Site Metadata
#---------------------------------------------------------------------
baseURL = 'https://docs.nephio.org/'
languageCode = 'en-us'
title = 'Nephio Documentation'
copyright = "The Nephio Authors"
enableGitInfo = true # Allows the theme to use version control information

#---------------------------------------------------------------------
# Content & Build Settings
#---------------------------------------------------------------------
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

# Hugo Module Settings
[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  # Import the Docsy theme and its dependencies
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

# Minification Settings
[minify]
  disableXML = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false

# Markdown Rendering Settings
[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = true
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allow unsafe HTML for Docsy's shortcodes
    [markup.highlight]
      style = "tango"
      guessSyntax = true
      prism_syntax_highlighting = true

#---------------------------------------------------------------------
# Docsy Theme Parameters
#---------------------------------------------------------------------
[params]
code_of_conduct = "https://lfprojects.org/policies/code-of-conduct/"

# --- Versioning ---
version_menu = "Releases"
archived_version = false
version = "main"
url_latest_version = "https://docs.nephio.org/docs/"

# --- Repository Links ---
github_repo = "https://github.com/nephio-project/docs"
github_project_repo = "https://github.com/nephio-project/nephio"

# --- UI Configuration ---
[params.ui]
sidebar_menu_compact = true
ul_show = 1
breadcrumb_disable = false
sidebar_search_disable = false
sidebar_menu_foldable = true
navbar_logo = true

# --- Doc Feedback ---
[params.ui.feedback]
enable = false
yes = 'Glad to hear it! Please <a href="https://github.com/nephio-project/nephio/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/nephio-project/nephio/issues/new">tell us how we can improve</a>.'

# --- Reading Time ---
[params.ui.readingtime]
enable = false

# --- Footer Links ---
[params.links]
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/nephio-project/nephio"
	icon = "fab fa-github"
    desc = "Development takes place here!"

#---------------------------------------------------------------------
# Search Settings
#---------------------------------------------------------------------
offlineSearch = true
offlineSearchSummaryLength = 70
offlineSearchMaxResults = 10

#---------------------------------------------------------------------
# Other Settings
#---------------------------------------------------------------------
# Time format
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"

# RSS feed
rss_sections = ["blog"]

#---------------------------------------------------------------------
# Release Versions
#---------------------------------------------------------------------
[[params.versions]]
  version = "main"
  url = "https://docs.nephio.org/docs/"

[[params.versions]]
  version = "R4"
  url = "https://r4.docs.nephio.org/docs/"

[[params.versions]]
  version = "R3"
  url = "https://r3.docs.nephio.org/docs/"

[[params.versions]]
  version = "R2"
  url = "https://r2.docs.nephio.org/docs/"

[[params.versions]]
  version = "R1"
  url = "https://github.com/nephio-project/docs/tree/R1"
